
/* ~bad_exception() const */

void __thiscall std::bad_exception::~bad_exception(bad_exception *this)

{
  return;
}

