
/* ~exception() const */

void __thiscall std::exception::~exception(exception *this)

{
  return;
}

